### ISSUE TITLE
Left and right button presses when viewing the f/shutter should change the current priority value

### ISSUE THREAD

**Issue by sadiqawos** [sadiqawos/micro_light_meter#5]
Left and right button presses when viewing the f/shutter (outside of menu) should change the current priority value up and down, and recalculate the driven value.

**Comment by mattthegamer463** [comment]
OK, so the way it works right now is the reading is converted to EV, then there is a formula I created which takes the given values (ISO, aperture, shutter speed) and computes an EV of its own.  The strings stored in the arrays along with the labels for those 3 things are the weighted values for them.  It's pretty convoluted.

Once the "Calculated Exposure Value" (CEV) is calculated, its checked against the measured EV and the driven value (in this case right now, only shutter speed is drive-able) it will subtract as needed from the shutter array pointer to make the numbers match.  Then it displays the strings for the values on the screen.

The equation is Shutter + aperture + iso = calculed EV.  

The lines in question are basically 343 to 355.  Right now its a shitty do/while loop instead of just subtracting the difference to match the CEV and MEV (measured EV) directly.

**Comment by sadiqawos** [comment]
https://github.com/sadiqawos/micro_light_meter/pull/2/commits/81a98f9194ec6cac92acd9e17d38d8f45d9b3fb3

**Comment by mattthegamer463** [comment]
Doesn't work.
